 
itemdb= {
        0x00 : "Nirai Impulse EX 1",
        0x01 : "Nirai Impulse EX 2",
        0x02 : "Nirai Charged Pulse",
        0x03 : "V'skorr",
        0x04 : "Sh'koom",
        0x05 : "Berger Focus I",
        0x06 : "Berger Focus II A1",
        0x07 : "Berger Retribution",
        0x08 : "Berger Converge IV",
        0x09 : "M6 A1 \"Wolf\"",
        0x0A : "M6 A2 \"Cougar\"",
        0x0B : "M6 A3 \"Wolverine\"",
        0x0C : "N'saan",
        0x0D : "K'booskk",
        0x0E : "Sh'gaal",
        0x0F : "H'nookk",
        0x10 : "Luna EMP Mk I",
        0x11 : "Sol EMP Mk II",
        0x12 : "Dia EMP Mk III",
        0x13 : "Gram Blaster",
        0x14 : "Ridil Blaster",
        0x15 : "Tyrfing Blaster",
        0x16 : "Micro Gun MK I",
        0x17 : "Micro Gun MKII",
        0x18 : "64MJ Railgun",
        0x19 : "128MJ Railgun",
        0x1A : "Scram Cannon",
        0x1B : "Mass Driver MD 10",
        0x1C : "Thermic o5",
        0x1D : "ReHeat o10",
        0x1E : "MaxHeat o20",
        0x1F : "G'liissk",
        0x20 : "Jet Rocket",
        0x21 : "Amour Rocket",
        0x22 : "EMP Rocket Mk I",
        0x23 : "EMP Rocket Mk II",
        0x24 : "Edo",
        0x25 : "Intelli Jet",
        0x26 : "S'koonn",
        0x27 : "Mamba EMP",
        0x28 : "Dephase EMP",
        0x29 : "EMP GL I",
        0x2A : "EMP GL II",
        0x2B : "EMP GL DX",
        0x2C : "AMR Tormentor",
        0x2D : "AMR Oppressor",
        0x2E : "AMR Extinctor",
        0x2F : "Hammerhead D1",
        0x30 : "Hammerhead D2A2",
        0x31 : "L'ksaar",
        0x32 : "Targe Shield",
        0x33 : "Riot Shield",
        0x34 : "H'Belam",
        0x35 : "Beamshield II",
        0x36 : "Fluxed Matter Shield",
        0x37 : "E2 Exoclad",
        0x38 : "E4 Ultra Lamina",
        0x39 : "E6 D-X Plating",
        0x3A : "D'iol",
        0x3B : "T'yol",
        0x3C : "AMR Saber",
        0x3D : "Neétha EMP",
        0x3E : "Ksann'k",
        0x3F : "ZMI Optistore",
        0x40 : "Autopacker 2",
        0x41 : "Ultracompact",
        0x42 : "Shrinker BT",
        0x43 : "Rhoda Blackhole",
        0x44 : "AB-1 \"Retractor\"",
        0x45 : "AB-2 \"Glue Gun\"",
        0x46 : "AB-3 \"Kingfisher\"",
        0x47 : "Linear Boost",
        0x48 : "Cyclotron Boost",
        0x49 : "Synchrotron Boost",
        0x4A : "Me'al",
        0x4B : "Ketar Repair Bot",
        0x4C : "Static Thrust",
        0x4D : "Pendular Thrust",
        0x4E : "D'ozzt Thrust",
        0x4F : "Mp'zzzm Thrust",
        0x50 : "Pulsed Plasma Thrust",
        0x51 : "Telta Quickscan",
        0x52 : "Telta Ecoscan",
        0x53 : "Hiroto Proscan",
        0x54 : "Hiroto Ultrascan",
        0x55 : "Khador Drive",
        0x56 : "IMT Extract 1.3",
        0x57 : "IMT Extract 2.7",
        0x58 : "K'yuul",
        0x59 : "IMT Extract 4.0X",
        0x5A : "Gunant's Drill",
        0x5B : "Small Cabin",
        0x5C : "Medium Cabin",
        0x5D : "Large Cabin",
        0x5E : "Sight Suppressor II",
        0x5F : "U'tool",
        0x60 : "Yin Co. Shadow Ninja",
        0x61 : "Drinking Water",
        0x62 : "Medical Supplies",
        0x63 : "Space Waste",
        0x64 : "Artifacts",
        0x65 : "Rare Animals",
        0x66 : "Rare Plants",
        0x67 : "Drugs",
        0x68 : "Luxury",
        0x69 : "Premium Food",
        0x6A : "Basic Food",
        0x6B : "Organs",
        0x6C : "Vossk Organs",
        0x6D : "Buskat",
        0x6E : "Collectible Figure",
        0x6F : "Digital Watch",
        0x70 : "Towels",
        0x71 : "Implants",
        0x72 : "Explosives",
        0x73 : "Documents",
        0x74 : "Secure Cabin/Container",
        0x75 : "Secure Cabin/Container",
        0x76 : "Electronics",
        0x77 : "Chemicals",
        0x78 : "Plastics",
        0x79 : "Nanotech",
        0x7A : "Energy Cells",
        0x7B : "Biowaste",
        0x7C : "Radioactive Goods",
        0x7D : "Mechanical Supplies",
        0x7E : "Noble Gas",
        0x7F : "Microchips",
        0x80 : "Com. Devices",
        0x81 : "Optics",
        0x82 : "Hydraulics",
        0x83 : "Alien Remains",
        0x84 : "Suteo Liqueur",
        0x85 : "Pan Whiskey",
        0x86 : "Behén Wine",
        0x87 : "V'ikka Moonshine",
        0x88 : "Eanya Tonic",
        0x89 : "S'kolptorr Rum",
        0x8A : "Wolf-Reiser Brandy",
        0x8B : "Aquila Cocktail",
        0x8C : "Buntta Apéritif",
        0x8D : "Weymire Punch",
        0x8E : "Y'mirr Schnapps",
        0x8F : "Union Draught",
        0x90 : "Oom'bak Gin",
        0x91 : "Vulpes Soup",
        0x92 : "Magnetar Juice",
        0x93 : "Mido Distillate",
        0x94 : "Prospero Flip",
        0x95 : "Nesla Brandy",
        0x96 : "Pescal Inartu Brew",
        0x97 : "Augmenta Fizz",
        0x98 : "K'ontrr Dishwater",
        0x99 : "Ni'mrrod Muck",
        0x9A : "Gold",
        0x9B : "Titanium",
        0x9C : "Iron",
        0x9D : "Orichalzine",
        0x9E : "Pyresium",
        0x9F : "Sodil",
        0xA0 : "Doxtrite",
        0xA1 : "Cesogen",
        0xA2 : "Perrius",
        0xA3 : "Hypanium",
        0xA4 : "Void Crystals",
        0xA5 : "Golden Core",
        0xA6 : "Titanium Core",
        0xA7 : "Iron Core",
        0xA8 : "Orichalzine Core",
        0xA9 : "Pyresium Core",
        0xAA : "Sodil Core",
        0xAB : "Doxtrite Core",
        0xAC : "Cesogen Core",
        0xAD : "Perrius Core",
        0xAE : "Hypanium Core",
        0xAF : "Void Essence",
        0xB0 : "Nirai .50AS",
        0xB1 : "Berger FlaK 9-9",
        0xB2 : "Icarus Heavy AS",
        0xB3 : "Liberator",
        0xB4 : "Berger AGT 20mm ",
        0xB5 : "Skuld AT XR",
        0xB6 : "HH-AT \"Archimedes\"",
        0xB7 : "Disruptor Laser",
        0xB8 : "Rhoda Vortex",
        0xB9 : "Emergency System",
        0xBA : "Nirai Overdrive",
        0xBB : "Nirai Overcharge",
        0xBC : "Ketar Repair Bot II",
        0xBD : "Signature: Terran",
        0xBE : "Signature: Vossk",
        0xBF : "Signature: Nivelian",
        0xC0 : "Signature: Midorian",
        0xC1 : "SunFire o50",
        0xC2 : "AB-4 \"Octopus\"",
        0xC3 : "Polytron Boost"
        }
